<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$helper = $this->helper('shoppersettings/image');

$imgX = 252;
$imgY = $helper->calculateHeight($imgX);
?>
<?php if($_productCollection->count()): ?>
<div class="category-products">
    <h2><?php echo $this->__($this->getBlockTitle());?></h2>
    <?php $_collectionSize = $_productCollection->count(); ?>
    <ul class="products-grid">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item">

            <div class="regular">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?>
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX*2, $imgY*2) ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
            </a>
            <div class="button-container">
                <?php if($_product->isSaleable()): ?>
                <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
            </div>
            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
            <?php echo $this->getPriceHtml($_product, true) ?>
            </div>

            <div class="hover">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?>
                <?php
                $back_img = $_product->getMediaGalleryImages()->getItemByColumnValue('label', 'back');
                if ( $back_img ) : ?>
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($imgX, $imgY) ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($imgX*2, $imgY*2) ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                    <?php else : ?>
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX*2, $imgY*2) ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                    <?php endif; ?>
            </a>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                <?php echo $this->helper('shoppersettings/data')->priceFormat( $this->getPriceHtml($_product, true) ); ?>
            </a>
            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
            <?php if($_product->getRatingSummary()){ echo $this->getReviewsSummaryHtml($_product); } ?>
            <div class="button-container">
                <?php if($_product->isSaleable()): ?>
                <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><em></em><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
            </div>

            <ul class="add-to-links">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><span>+</span><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if ($_compareUrl=$this->getAddToCompareUrl($_product)) : ?>
                <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><span>+</span><?php echo $this->__('Add to Compare') ?></a></li>
                <?php endif; ?>
            </ul>

            </div>

        </li>
    <?php endforeach ?>
    </ul>
</div>
<?php endif; ?>
